version: '3.8'

services:
  web:
    container_name: joni_web
    restart: always
    build: .
    expose:
      - 8000
    env_file: production.env
    volumes:
      
      - static_volume:/usr/src/app/staticfiles
      - joni_media_data:/usr/src/app/media
    links:
      - postgres:postgres
    command: sh '/usr/src/app/run_web.sh'

   

  postgres:
    container_name: joni_postgres
    restart: always
    image: postgres:latest
    env_file: production.env
    ports:
      - 23433:5432
    volumes:
      - joni_postgres:/var/lib/postgresqql/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - joni_media_data:/usr/src/app/media
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  joni_postgres:
  static_volume:
  joni_media_data: