web:
  container_name: joni_web
  restart: always
  build: .
  ports:
    - 23030:8000
  expose:
    - 8000
  env_file: production.env
  volumes:
    - joni_media_data:/usr/src/app/media
  links:
    - postgres:postgres
  command: sh '/usr/src/app/run_web.sh'

postgres:
  container_name: joni_postgres
  restart: always
  image: postgres:latest
  env_file: production.env
  ports:
    - 23433:5432
  volumes:
    - joni_postgres:/var/lib/postgresqql/data/