# Generated by Django 4.0.6 on 2022-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_page_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
