# Generated by Django 4.0.6 on 2022-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_service_main_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
