# Generated by Django 4.0.6 on 2022-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_service_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_title',
            field=models.CharField(max_length=10),
        ),
    ]
