# Generated by Django 4.0.6 on 2022-07-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_testimonial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
