# Generated by Django 4.0.6 on 2022-07-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_testimonial_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_profile_img',
            field=models.ImageField(default='client_profile_img/profile_img.png', upload_to='client_profile_img/'),
        ),
    ]
