# Generated by Django 4.0.6 on 2022-08-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
