# Generated by Django 4.0.6 on 2022-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_testimonial_client_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquired_for',
            field=models.CharField(blank=True, choices=[('Search Engine Optimization', 'Search Engine Optimization'), ('Social Media Opitimization', 'Social Media Opitimization'), ('Search Engine Marketing', 'Search Engine Marketing'), ('App Store Opitimization', 'App Store Opitimization'), ('Web Development', 'Web Development'), ('App Development', 'App Development'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
