# Generated by Django 3.2.15 on 2022-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20220809_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url_title',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
