# Generated by Django 3.2.15 on 2022-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_service_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.TextField(null=True),
        ),
    ]
