# Generated by Django 3.2.15 on 2022-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20220827_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('meta_title', models.TextField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keywords', models.TextField(null=True)),
            ],
        ),
    ]
